In [1]:
import pandas as pd 
import numpy as np
import statsmodels.api as sm
import seaborn as sns 
sns.set()
import matplotlib.pyplot as plt

In [2]:
raw_data = pd.read_csv("C:/Users/LENOVO/Downloads/Bank_data (2).csv")
data = raw_data.copy()
data

Unnamed: 0  interest_rate  credit  march  may  previous  duration    y
0             0          1.334     0.0    1.0  0.0       0.0     117.0   no
1             1          0.767     0.0    0.0  2.0       1.0     274.0  yes
2             2          4.858     0.0    1.0  0.0       0.0     167.0   no
3             3          4.120     0.0    0.0  0.0       0.0     686.0  yes
4             4          4.856     0.0    1.0  0.0       0.0     157.0   no
..          ...            ...     ...    ...  ...       ...       ...  ...
513         513          1.334     0.0    1.0  0.0       0.0     204.0   no
514         514          0.861     0.0    0.0  2.0       1.0     806.0  yes
515         515          0.879     0.0    0.0  0.0       0.0     290.0   no
516         516          0.877     0.0    0.0  5.0       1.0     473.0  yes
517         517          4.965     0.0    0.0  0.0       0.0     142.0   no

[518 rows x 8 columns]

In [3]:
data['y'] = data['y'].map({'yes':1,'no':0})
data=data.drop('Unnamed: 0',axis=1)
data

interest_rate  credit  march  may  previous  duration  y
0            1.334     0.0    1.0  0.0       0.0     117.0  0
1            0.767     0.0    0.0  2.0       1.0     274.0  1
2            4.858     0.0    1.0  0.0       0.0     167.0  0
3            4.120     0.0    0.0  0.0       0.0     686.0  1
4            4.856     0.0    1.0  0.0       0.0     157.0  0
..             ...     ...    ...  ...       ...       ... ..
513          1.334     0.0    1.0  0.0       0.0     204.0  0
514          0.861     0.0    0.0  2.0       1.0     806.0  1
515          0.879     0.0    0.0  0.0       0.0     290.0  0
516          0.877     0.0    0.0  5.0       1.0     473.0  1
517          4.965     0.0    0.0  0.0       0.0     142.0  0

[518 rows x 7 columns]

In [4]:
y = data['y']
x1 = data[['duration','interest_rate','credit','march','may']]
x = sm.add_constant(x1)
reg_log = sm.Logit(y,x)
results_log = reg_log.fit()

Optimization terminated successfully.
         Current function value: 0.335942
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      511
Method:                           MLE   Df Model:                            6
Date:                Fri, 05 Jul 2024   Pseudo R-squ.:                  0.5153
Time:                        02:11:39   Log-Likelihood:                -174.02
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 7.579e-77
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -0.1385      0.339     -0.408      0.683      -0.804       0.527
duration          0.0070      0.001      9.386      0.000       0.006       0.008
interest_rate    -0.7802      0.092     -8.471      0.000      -0.961      -0.600
credit            2.4028      1.090      2.205      0.027       0.267       4.538
march            -1.8097      0.332     -5.459      0.000      -2.459      -1.160
may               0.1946      0.229      0.849      0.396      -0.255       0.644
previous          1.2746      0.583      2.186      0.029       0.132       2.417
=================================================================================
"""

In [6]:
np.set_printoptions(formatter ={'float': lambda x:'{0:0.2f}'.format(x)} )
results_log.predict()

array([0.10, 0.94, 0.01, 0.81, 0.01, 0.56, 0.03, 0.00, 0.71, 0.07, 0.95,
       0.47, 0.90, 0.10, 0.08, 0.81, 0.88, 0.84, 0.36, 0.76, 0.97, 0.88,
       0.13, 0.10, 0.63, 0.08, 0.79, 0.75, 0.89, 0.04, 0.02, 0.12, 0.28,
       0.74, 0.06, 0.01, 0.99, 0.06, 1.00, 0.53, 0.06, 0.83, 0.06, 0.01,
       0.85, 0.57, 0.00, 0.14, 0.15, 0.81, 0.72, 0.05, 0.03, 0.05, 0.01,
       0.84, 0.09, 0.83, 0.98, 0.82, 0.04, 0.11, 0.99, 0.75, 0.16, 0.30,
       0.05, 0.06, 1.00, 0.08, 0.02, 0.77, 0.14, 0.97, 0.88, 0.12, 0.65,
       0.05, 0.01, 0.03, 0.90, 0.84, 0.89, 0.13, 0.22, 0.98, 0.62, 0.85,
       0.72, 0.03, 0.08, 0.03, 0.69, 0.62, 0.94, 0.98, 0.97, 0.03, 0.98,
       0.06, 0.99, 0.07, 0.99, 0.67, 0.28, 0.35, 0.19, 0.68, 0.78, 0.03,
       0.99, 0.44, 0.17, 0.06, 0.93, 0.02, 0.04, 0.89, 0.49, 0.14, 0.10,
       0.00, 0.93, 1.00, 0.32, 0.98, 0.93, 0.86, 0.72, 0.65, 0.05, 0.25,
       0.80, 0.80, 0.85, 0.09, 0.22, 0.72, 0.11, 0.01, 0.01, 0.01, 0.24,
       0.78, 0.23, 1.00, 0.22, 0.01, 1.00, 0.61, 0.

In [7]:
cm = results_log.pred_table()

In [8]:
accuracy_train = (cm[0,0]+cm[1,1])/cm.sum()

In [9]:
accuracy_train

0.8648648648648649

In [10]:
test = pd.read_csv("C:/Users/LENOVO/Downloads/Bank_data_testing.csv")
test['y'] = test['y'].map({'yes':1,'no':0})
test

Unnamed: 0  interest_rate  credit  march  may  previous  duration  y
0             0          1.313     0.0    1.0  0.0       0.0     487.0  0
1             1          4.961     0.0    0.0  0.0       0.0     132.0  0
2             2          4.856     0.0    1.0  0.0       0.0      92.0  0
3             3          4.120     0.0    0.0  0.0       0.0    1468.0  1
4             4          4.963     0.0    0.0  0.0       0.0      36.0  0
..          ...            ...     ...    ...  ...       ...       ... ..
217         217          4.963     0.0    0.0  0.0       0.0     458.0  1
218         218          1.264     0.0    1.0  1.0       0.0     397.0  1
219         219          1.281     0.0    1.0  0.0       0.0      34.0  0
220         220          0.739     0.0    0.0  2.0       0.0     233.0  0
221         221          1.046     0.0    0.0  0.0       0.0     238.0  1

[222 rows x 8 columns]

In [11]:
test_actual = test['y']
test=test.drop('y',axis=1)
test=test.drop('Unnamed: 0',axis=1)

In [12]:
def confusion_matrix(data,actual_values,model):
        
        # Confusion matrix 
        
        # Parameters
        # ----------
        # data: data frame or array
            # data is a data frame formatted in the same way as your input data (without the actual values)
            # e.g. const, var1, var2, etc. Order is very important!
        # actual_values: data frame or array
            # These are the actual values from the test_data
            # In the case of a logistic regression, it should be a single column with 0s and 1s
            
        # model: a LogitResults object
            # this is the variable where you have the fitted model 
            # e.g. results_log in this course
        # ----------
        
        #Predict the values using the Logit model
        pred_values = model.predict(data)
        # Specify the bins 
        bins=np.array([0,0.5,1])
        # Create a histogram, where if values are between 0 and 0.5 tell will be considered 0
        # if they are between 0.5 and 1, they will be considered 1
        cm = np.histogram2d(actual_values, pred_values, bins=bins)[0]
        # Calculate the accuracy
        accuracy = (cm[0,0]+cm[1,1])/cm.sum()
        # Return the confusion matrix and 
        return cm, accuracy

In [13]:
test_data = sm.add_constant(test)
test_data = test_data[x.columns.values]
test_data

const  duration  interest_rate  credit  march  may  previous
0      1.0     487.0          1.313     0.0    1.0  0.0       0.0
1      1.0     132.0          4.961     0.0    0.0  0.0       0.0
2      1.0      92.0          4.856     0.0    1.0  0.0       0.0
3      1.0    1468.0          4.120     0.0    0.0  0.0       0.0
4      1.0      36.0          4.963     0.0    0.0  0.0       0.0
..     ...       ...            ...     ...    ...  ...       ...
217    1.0     458.0          4.963     0.0    0.0  0.0       0.0
218    1.0     397.0          1.264     0.0    1.0  1.0       0.0
219    1.0      34.0          1.281     0.0    1.0  0.0       0.0
220    1.0     233.0          0.739     0.0    0.0  2.0       0.0
221    1.0     238.0          1.046     0.0    0.0  0.0       0.0

[222 rows x 7 columns]

In [14]:
confusion_matrix(test_data,test_actual,results_log)

(array([[94.00, 17.00],
        [12.00, 99.00]]),
 0.8693693693693694)

In [15]:
confusion_matrix(x,y,results_log)

(array([[220.00, 39.00],
        [31.00, 228.00]]),
 0.8648648648648649)