In [1]:
import numpy as np

In [2]:
5+5

10

In [3]:
10-4

6

In [4]:
m1 = np.array([12,3,4,5])
m2 = np.arange(1,7)
m2

array([1, 2, 3, 4, 5, 6])

In [5]:
m1+m2 # different shapes cant be added together 

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [6]:
m2 + 1

array([2, 3, 4, 5, 6, 7])

In [7]:
m2 + np.array([1])

array([2, 3, 4, 5, 6, 7])

In [8]:
A  = np.array([[5,6,8],[1,9,3]])
A

array([[5, 6, 8],
       [1, 9, 3]])

In [9]:
A.T

array([[5, 1],
       [6, 9],
       [8, 3]])

In [10]:
B = np.array([[1,6,7],[7,8,-2]])
B.T

array([[ 1,  7],
       [ 6,  8],
       [ 7, -2]])

In [12]:
s = np.array([5])
s.T

array([5])

In [13]:
x =np.array([1,2,3])
x

array([1, 2, 3])

In [14]:
x.T

array([1, 2, 3])

In [15]:
x.shape

(3,)

In [18]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [19]:
x.T

array([1, 2, 3])

In [20]:
C = np.array([2,8,-4])
D = np.array([1,-7,3])
np.dot(C,D)

-66

In [21]:
v = np.arange(2,7)
u = np.arange(3,8)
np.dot(u,v)

110

In [24]:
np.dot(A,B.T)

array([[97, 67],
       [76, 73]])