In [1]:
import numpy as np

In [2]:
s  = 5 

In [3]:
s

5

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

In [8]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [12]:
type(m) # n - dimensional array

numpy.ndarray

In [13]:
s_array = np.array(5)

In [15]:
type(s_array)#scalar

numpy.ndarray

In [16]:
m.shape

(2, 3)

In [17]:
v.shape

(3,)

In [18]:
s_array.shape

()

In [19]:
m1 = np.array([[5,12,6],[-3,4,5]])
m2 =np.array([[4,3,7],[2,5,9]])
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  4,  5]],

       [[ 4,  3,  7],
        [ 2,  5,  9]]])

In [20]:
t.shape

(2, 2, 3)

In [21]:
m1+m2

array([[ 9, 15, 13],
       [-1,  9, 14]])

In [22]:
m1-m2

array([[ 1,  9, -1],
       [-5, -1, -4]])

In [23]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,7,4,9,1])
v1-v2

array([-1, -5, -1, -5,  4])

In [24]:
v1+v2

array([ 3,  9,  7, 13,  6])