In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("C:/Users/LENOVO/Downloads/real_estate_price_size_year (1).csv")
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [4]:
y = data['price']
x= data[['size','year']]
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [5]:
reg.score(x,y)

0.7764803683276793

In [6]:
def adjusted_R_squared(x,y):
    R2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    return (1-(1-R2)*(n-1)/(n-p-1))

In [7]:
adjusted_R_squared(x,y)

0.77187171612825

In [8]:
reg.intercept_

-5772267.01746328

In [9]:
reg.coef_

array([ 227.70085401, 2916.78532684])

## Feature Selection


In [10]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [11]:
p_values = f_regression(x,y)[1]
p_values.round(3)

array([0.   , 0.357])

In [12]:
# YEAR is not significant 

In [20]:
new_data  = pd.DataFrame(data=[[750,2009]],columns=[['size','year']])
new_data

size  year
0  750  2009

In [21]:
reg.predict(new_data.values)

C:\Users\LENOVO\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([258330.34465995])

## Creating a summary table

In [13]:
reg_summary = pd.DataFrame(data = ['size','year'],columns=['Feature'])
reg_summary

Feature
0    size
1    year

In [15]:
reg_summary['coefficients']=reg.coef_
reg_summary['p_values'] = p_values

In [16]:
reg_summary

Feature  coefficients      p_values
0    size    227.700854  8.127632e-31
1    year   2916.785327  3.573408e-01

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [25]:
scaler.fit(x)

StandardScaler()

In [26]:
x_scaled = scaler.transform(x)

In [27]:
x_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

In [29]:
reg_new = LinearRegression()
reg_new.fit(x_scaled,y)

LinearRegression()

In [30]:
new_data  = pd.DataFrame(data =[[750,2010]],columns = ['size','year'])
new_data

size  year
0   750  2010

In [31]:
new_data_scaled = scaler.transform(new_data)

In [32]:
new_data_scaled

array([[-0.34752816, -0.55256648]])

In [33]:
reg_new.predict(new_data_scaled)

array([261247.12998678])

In [34]:
f_regression(x_scaled,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

# from P value we reject 'year' feature

In [35]:
reg_newer = LinearRegression()
reg_newer.fit(x_scaled[:,0].reshape(-1,1),y)

LinearRegression()

In [41]:
reg_newer.predict(new_data_scaled[:,0].reshape(-1,1))

array([269296.65874718])