In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("C:/Users/LENOVO/Downloads/1.02.+Multiple+linear+regression (3).csv")
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [32]:
y=data['GPA']
x = data[['SAT','Rand 1,2,3']]

# Standardization

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [34]:
scaler.fit(x)

StandardScaler()

In [35]:
x_scaled = scaler.transform(x)

In [36]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [37]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [38]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [39]:
reg.intercept_

3.330238095238095

In [40]:
reg_summary = pd.DataFrame(data = ['Bias','SAT','Rand 1,2,3'],columns=['Features'])
reg_summary['weights']=reg.intercept_,reg.coef_[0],reg.coef_[1]
reg_summary

Features   weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

# Predicting


In [41]:
new_data = pd.DataFrame(data = [[1700,1],[1800,2]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           1
1  1800           2

In [42]:
reg.predict(new_data.values)

array([295.40682569, 312.5811849 ])

In [43]:
new_data_scaled = scaler.transform(new_data)

In [46]:
reg.predict(new_data_scaled)

array([3.09878385, 3.25586821])

# Removing the useless feature

In [47]:
reg_simple = LinearRegression()

In [49]:
x_simple  = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple,y)

LinearRegression()

In [51]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])